import { JobListing } from "./types";

export const mockJobs: JobListing[] = [
  {
    id: "1",
    title: "Customer Service Representative",
    employer: "United Healthcare",
    location: "Remote",
    isRemote: true,
    salary: { min: 17, max: 21, period: "hourly" },
    employmentType: "FULLTIME",
    description: "Handle customer inquiries about health insurance plans. Help members understand their benefits, find doctors, and resolve billing questions. Full training provided.",
    qualifications: ["High school diploma or GED", "Customer service experience", "Basic computer skills", "Good communication skills"],
    benefits: ["Health insurance", "Dental & vision", "401k with match", "Paid time off", "Work from home"],
    postedDaysAgo: 2,
    category: "customer_service",
  },
  {
    id: "2",
    title: "Warehouse Associate",
    employer: "Amazon",
    location: "Dallas, TX",
    isRemote: false,
    salary: { min: 18, max: 22, period: "hourly" },
    employmentType: "FULLTIME",
    description: "Pick, pack, and ship customer orders in a fast-paced warehouse. Day and night shifts available. No experience needed — we train you.",
    qualifications: ["Must be 18+", "Able to lift 50 lbs", "Able to stand for 8+ hours", "No experience required"],
    benefits: ["Health insurance from day 1", "401k", "Paid time off", "Career advancement programs", "Tuition assistance"],
    postedDaysAgo: 1,
    category: "warehouse",
  },
  {
    id: "3",
    title: "Medical Assistant",
    employer: "Baylor Scott & White",
    location: "Austin, TX",
    isRemote: false,
    salary: { min: 16, max: 20, period: "hourly" },
    employmentType: "FULLTIME",
    description: "Support doctors and nurses with patient care in a busy clinic. Take vitals, update patient records, and help patients feel comfortable. Great entry into healthcare.",
    qualifications: ["Medical assistant certificate (or willingness to get one)", "CPR certification", "Compassionate and patient", "Basic computer skills"],
    benefits: ["Health insurance", "Dental & vision", "Tuition reimbursement", "Paid time off", "Retirement plan"],
    postedDaysAgo: 3,
    category: "healthcare_support",
  },
  {
    id: "4",
    title: "IT Help Desk Technician",
    employer: "Randstad (at Dell)",
    location: "Round Rock, TX",
    isRemote: false,
    salary: { min: 19, max: 24, period: "hourly" },
    employmentType: "FULLTIME",
    description: "Help employees solve computer problems over the phone and in person. Reset passwords, install software, and fix basic tech issues. CompTIA A+ preferred but not required.",
    qualifications: ["Interest in technology", "Problem-solving skills", "Good communication", "CompTIA A+ preferred but not required"],
    benefits: ["Health insurance", "Paid training", "Career growth opportunities", "Flexible schedule"],
    postedDaysAgo: 5,
    category: "admin",
  },
  {
    id: "5",
    title: "Retail Team Lead",
    employer: "Target",
    location: "Houston, TX",
    isRemote: false,
    salary: { min: 18, max: 22, period: "hourly" },
    employmentType: "FULLTIME",
    description: "Lead a team of 5-10 associates on the sales floor. Open or close the store, coach team members, and ensure great guest experiences. Perfect for someone ready to step up.",
    qualifications: ["1+ year retail experience", "Leadership skills", "Flexible schedule (weekends required)", "High school diploma"],
    benefits: ["Health insurance", "10% employee discount", "401k", "Tuition reimbursement", "Paid time off"],
    postedDaysAgo: 2,
    category: "retail",
  },
  {
    id: "6",
    title: "CDL Truck Driver - Local Routes",
    employer: "Sysco",
    location: "San Antonio, TX",
    isRemote: false,
    salary: { min: 24, max: 30, period: "hourly" },
    employmentType: "FULLTIME",
    description: "Drive local delivery routes — home every night. Deliver food products to restaurants and businesses. CDL required. Great pay with overtime opportunities.",
    qualifications: ["CDL Class A or B license", "Clean driving record", "Able to lift 50+ lbs", "1 year driving experience preferred"],
    benefits: ["Health insurance", "Weekly pay", "Overtime available", "Retirement plan", "Home every night"],
    postedDaysAgo: 1,
    category: "delivery",
  },
  {
    id: "7",
    title: "Certified Nursing Assistant (CNA)",
    employer: "Brookdale Senior Living",
    location: "Fort Worth, TX",
    isRemote: false,
    salary: { min: 15, max: 19, period: "hourly" },
    employmentType: "FULLTIME",
    description: "Care for seniors in an assisted living community. Help with daily activities, meals, and companionship. CNA certification required. Very rewarding work.",
    qualifications: ["CNA certification", "CPR certification", "Compassion and patience", "Able to lift and move residents"],
    benefits: ["Health insurance", "Paid CNA renewal", "Shift differentials", "Employee assistance program", "Career advancement"],
    postedDaysAgo: 4,
    category: "healthcare_support",
  },
  {
    id: "8",
    title: "Bank Teller",
    employer: "Chase",
    location: "Dallas, TX",
    isRemote: false,
    salary: { min: 17, max: 20, period: "hourly" },
    employmentType: "FULLTIME",
    description: "Help customers with everyday banking — deposits, withdrawals, account questions. Great stepping stone into banking and finance. No banking experience needed.",
    qualifications: ["High school diploma", "Cash handling experience helpful", "Customer service skills", "Attention to detail"],
    benefits: ["Health insurance", "401k with match", "Tuition reimbursement", "Paid time off", "Banking perks"],
    postedDaysAgo: 3,
    category: "customer_service",
  },
  {
    id: "9",
    title: "HVAC Apprentice",
    employer: "Service Experts",
    location: "Austin, TX",
    isRemote: false,
    salary: { min: 16, max: 20, period: "hourly" },
    employmentType: "FULLTIME",
    description: "Learn HVAC installation and repair from experienced technicians. Paid training while you work. No experience needed — just mechanical aptitude and willingness to learn.",
    qualifications: ["High school diploma or GED", "Valid driver's license", "Able to work in heat/cold", "Mechanical aptitude helpful"],
    benefits: ["Paid training", "Health insurance", "Tool allowance", "Company vehicle (after training)", "Advancement to journeyman"],
    postedDaysAgo: 6,
    category: "other",
  },
  {
    id: "10",
    title: "Phlebotomist",
    employer: "Quest Diagnostics",
    location: "Houston, TX",
    isRemote: false,
    salary: { min: 17, max: 22, period: "hourly" },
    employmentType: "FULLTIME",
    description: "Draw blood from patients for lab tests. Work in a clinical setting with a friendly team. Phlebotomy certification required — can be earned in as little as 4-8 weeks.",
    qualifications: ["Phlebotomy certification", "Excellent bedside manner", "Attention to detail", "Able to stand for long periods"],
    benefits: ["Health insurance", "401k", "Paid time off", "Continuing education", "Employee discount programs"],
    postedDaysAgo: 2,
    category: "healthcare_support",
  },
  {
    id: "11",
    title: "Administrative Assistant",
    employer: "UT Southwestern Medical Center",
    location: "Dallas, TX",
    isRemote: false,
    salary: { min: 16, max: 20, period: "hourly" },
    employmentType: "FULLTIME",
    description: "Support a team of doctors with scheduling, filing, phone calls, and data entry. Great benefits at a major medical center. Monday-Friday schedule.",
    qualifications: ["High school diploma", "Microsoft Office skills", "Organizational skills", "Professional phone manner"],
    benefits: ["Excellent health insurance", "Pension plan", "Generous PTO", "Tuition reimbursement", "Free parking"],
    postedDaysAgo: 4,
    category: "admin",
  },
  {
    id: "12",
    title: "Delivery Driver",
    employer: "FedEx Ground",
    location: "San Antonio, TX",
    isRemote: false,
    salary: { min: 18, max: 23, period: "hourly" },
    employmentType: "FULLTIME",
    description: "Deliver packages on a set daily route. Be active, be outside, and be done by early afternoon most days. No CDL required.",
    qualifications: ["Valid driver's license", "Clean driving record", "Able to lift 75 lbs", "21+ years old"],
    benefits: ["Weekly pay", "Health insurance", "Paid holidays", "Retirement savings", "Uniform provided"],
    postedDaysAgo: 1,
    category: "delivery",
  },
  {
    id: "13",
    title: "Dental Assistant",
    employer: "Aspen Dental",
    location: "Fort Worth, TX",
    isRemote: false,
    salary: { min: 17, max: 22, period: "hourly" },
    employmentType: "FULLTIME",
    description: "Assist dentists during procedures, take X-rays, and help patients feel comfortable. Certification is a plus but we also offer paid on-the-job training.",
    qualifications: ["High school diploma", "Dental assistant certification preferred", "Good with people", "Able to work Saturdays"],
    benefits: ["Health insurance", "Paid training", "Free dental care", "401k", "Continuing education"],
    postedDaysAgo: 5,
    category: "healthcare_support",
  },
  {
    id: "14",
    title: "Call Center Agent - Insurance",
    employer: "Progressive Insurance",
    location: "Remote",
    isRemote: true,
    salary: { min: 18, max: 22, period: "hourly" },
    employmentType: "FULLTIME",
    description: "Help customers with auto insurance quotes, policy changes, and claims. Work from home with a company-provided computer. Paid training for 6 weeks.",
    qualifications: ["High school diploma", "Customer service experience", "Reliable internet connection", "Quiet home workspace"],
    benefits: ["Work from home", "Health insurance", "401k with match", "Paid training", "Bonus opportunities"],
    postedDaysAgo: 3,
    category: "customer_service",
  },
  {
    id: "15",
    title: "Maintenance Technician",
    employer: "Greystar (Apartments)",
    location: "Austin, TX",
    isRemote: false,
    salary: { min: 18, max: 24, period: "hourly" },
    employmentType: "FULLTIME",
    description: "Handle repairs and maintenance at a luxury apartment complex. Plumbing, electrical, HVAC basics, and general handyman work. On-site apartment discount available.",
    qualifications: ["Basic maintenance skills", "Reliable transportation", "HVAC certification a plus", "Customer-friendly attitude"],
    benefits: ["Apartment discount (20% off)", "Health insurance", "Paid time off", "Tool allowance", "On-call bonus pay"],
    postedDaysAgo: 2,
    category: "other",
  },
  {
    id: "16",
    title: "Shift Manager",
    employer: "Chipotle",
    location: "Houston, TX",
    isRemote: false,
    salary: { min: 16, max: 19, period: "hourly" },
    employmentType: "FULLTIME",
    description: "Lead a team during your shift — manage food prep, customer service, and team scheduling. A path to General Manager ($50-60K salary). Leadership experience valued.",
    qualifications: ["1+ year food service experience", "Leadership skills", "Food handler's certificate", "Flexible schedule"],
    benefits: ["Free meals", "Health insurance", "Tuition reimbursement (up to $5,250/yr)", "Career path to GM", "Quarterly bonus"],
    postedDaysAgo: 1,
    category: "food_service",
  },
  {
    id: "17",
    title: "Security Officer",
    employer: "Allied Universal",
    location: "Dallas, TX",
    isRemote: false,
    salary: { min: 15, max: 18, period: "hourly" },
    employmentType: "FULLTIME",
    description: "Monitor building security, greet visitors, and patrol the premises. Multiple shifts available including overnight with shift differentials. Paid guard card training.",
    qualifications: ["18+ years old", "Clean background check", "Able to stand/walk for long periods", "No experience needed"],
    benefits: ["Health insurance", "Weekly pay", "Overtime available", "Paid training", "Advancement opportunities"],
    postedDaysAgo: 2,
    category: "other",
  },
  {
    id: "18",
    title: "Receptionist",
    employer: "Hilton Hotels",
    location: "San Antonio, TX",
    isRemote: false,
    salary: { min: 15, max: 18, period: "hourly" },
    employmentType: "FULLTIME",
    description: "Be the first friendly face guests see. Check people in, answer questions about the area, and solve problems. Great for people who love helping others.",
    qualifications: ["Customer service experience", "Professional appearance", "Basic computer skills", "Flexible schedule (nights/weekends)"],
    benefits: ["Free hotel stays worldwide", "Health insurance", "401k", "Career growth in hospitality", "Meal discounts"],
    postedDaysAgo: 3,
    category: "customer_service",
  },
  {
    id: "19",
    title: "Preschool Teacher Assistant",
    employer: "KinderCare Learning Centers",
    location: "Fort Worth, TX",
    isRemote: false,
    salary: { min: 13, max: 16, period: "hourly" },
    employmentType: "FULLTIME",
    description: "Help care for and teach children ages 3-5. Plan activities, read stories, and help little ones learn and grow. CDA credential a plus but not required.",
    qualifications: ["High school diploma", "Love of working with children", "Patience and creativity", "Pass background check"],
    benefits: ["Childcare discount (50% off)", "Health insurance", "Paid training", "CDA credential support", "Paid time off"],
    postedDaysAgo: 4,
    category: "childcare",
  },
  {
    id: "20",
    title: "Data Entry Clerk",
    employer: "Robert Half (at AT&T)",
    location: "Remote",
    isRemote: true,
    salary: { min: 16, max: 19, period: "hourly" },
    employmentType: "FULLTIME",
    description: "Enter and verify customer data in computer systems. Detail-oriented work you can do from home. Monday-Friday, regular business hours.",
    qualifications: ["Typing speed 40+ WPM", "Attention to detail", "Microsoft Excel skills", "Reliable internet"],
    benefits: ["Work from home", "Regular hours", "Weekly pay", "Health insurance", "Potential for permanent hire"],
    postedDaysAgo: 2,
    category: "admin",
  },
];

export function searchJobs(params: { query?: string; category?: string; employmentType?: string }): JobListing[] {
  let results = [...mockJobs];

  if (params.query) {
    const q = params.query.toLowerCase();
    results = results.filter(
      (job) =>
        job.title.toLowerCase().includes(q) ||
        job.employer.toLowerCase().includes(q) ||
        job.description.toLowerCase().includes(q) ||
        job.location.toLowerCase().includes(q)
    );
  }

  if (params.category) {
    results = results.filter((job) => job.category === params.category);
  }

  if (params.employmentType) {
    results = results.filter((job) => job.employmentType === params.employmentType);
  }

  return results;
}
